name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Build and test
    if: github.event_name != 'pull_request' || github.event.pull_request.user.login != 'dependabot[bot]' || github.actor == 'github-actions[bot]'
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Check formatting
        run: ./gradlew spotlessCheck

      - name: Build and generate coverage
        run: ./gradlew clean build jacocoTestReport

      - name: Run SonarCloud analysis
        if: env.SONAR_TOKEN != ''
        run: ./gradlew sonar --info